#!/usr/bin/env python3
"""Generates CycleTester/UiFonts.h: anti-aliased bitmap fonts for the touchscreen UI.

Source font: Inter (Rasmus Andersson, SIL Open Font License 1.1, https://rsms.me/inter), the closest free
relative of Apple's San Francisco. Each glyph is rendered once here with Pillow and stored as 4-bit coverage
(16 levels), so the sketch only blends two colours per pixel and needs no font library.

usage:  python3 tools/make_ui_font.py [path to the folder holding Inter-Medium.otf, Inter-SemiBold.otf, Inter-Bold.otf]
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

FONT_DIR = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/opentype/inter"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "CycleTester", "UiFonts.h")

FIRST, LAST = 32, 126
ALL = [chr(c) for c in range(FIRST, LAST + 1)]

# name, file, pixel size, characters kept (the others are stored empty to save flash)
FACES = [
    ("CAPTION", "Inter-Medium.otf",   13, ALL),
    ("BODY",    "Inter-SemiBold.otf", 16, ALL),
    ("TITLE",   "Inter-Bold.otf",     24, ALL),
    ("NUM",     "Inter-SemiBold.otf", 28, list("0123456789 /-+.,:OFfx")),
]

GAMMA = 0.80      # <1 makes light text on a dark background a little heavier, which blending in sRGB would otherwise thin out


def render_face(file, size, chars):
    font = ImageFont.truetype(os.path.join(FONT_DIR, file), size, layout_engine=ImageFont.Layout.BASIC)
    ascent, descent = font.getmetrics()
    line_h = ascent + descent
    cap = font.getbbox("H", anchor="ls")           # (l, t, r, b) relative to the baseline
    cap_h = -cap[1]

    digit_adv = max(round(font.getlength(d)) for d in "0123456789")
    glyphs = {}
    for ch in ALL:
        if ch not in chars:
            glyphs[ch] = None
            continue
        adv = round(font.getlength(ch))
        if ch.isdigit():
            adv = digit_adv                          # tabular digits: a counter does not jiggle as it changes
        canvas = Image.new("L", (size * 3, size * 3), 0)
        ImageDraw.Draw(canvas).text((size, size * 2), ch, font=font, fill=255, anchor="ls")
        bbox = canvas.getbbox()
        if bbox is None:                             # space
            glyphs[ch] = (0, 0, 0, 0, adv, b"")
            continue
        img = canvas.crop(bbox)
        w, h = img.size
        xoff = bbox[0] - size                        # relative to the pen position
        yoff = bbox[1] - size * 2                    # relative to the baseline (negative = above it)
        if ch.isdigit():
            xoff += (adv - round(font.getlength(ch))) // 2
        # keep the bitmap inside its advance cell so glyph cells never overlap
        if xoff < 0:
            xoff = 0
        adv = max(adv, xoff + w)
        px = [min(15, int(round(((v / 255.0) ** GAMMA) * 15))) for v in img.tobytes()]
        packed = bytearray()
        for i in range(0, len(px), 2):
            hi = px[i]
            lo = px[i + 1] if i + 1 < len(px) else 0
            packed.append((hi << 4) | lo)
        glyphs[ch] = (w, h, xoff, yoff, adv, bytes(packed))
    return ascent, descent, cap_h, glyphs


def main():
    out = []
    out.append("""// UiFonts.h - GENERATED by tools/make_ui_font.py. Do not edit by hand.
//
// Anti-aliased bitmap fonts for the touchscreen: Inter (SIL Open Font License 1.1, https://rsms.me/inter),
// 4 bits of coverage per pixel, printable ASCII 32..126. Digits all have the same width.
#pragma once
#include <Arduino.h>
#include <avr/pgmspace.h>

struct UiGlyph {
  uint8_t  w, h;        // size of the bitmap
  int8_t   xoff, yoff;  // bitmap's top-left relative to the pen position / the baseline
  uint8_t  adv;         // how far the pen moves (also the width of the glyph's cell)
  uint16_t offset;      // where the bitmap starts in the font's bitmap array (4 bits per pixel, two pixels per byte)
};

struct UiFont {
  const UiGlyph* glyphs;     // FONT_FIRST_CHAR..FONT_LAST_CHAR
  const uint8_t* bitmaps;
  uint8_t ascent;            // pixels from the top of a cell to the baseline
  uint8_t height;            // height of a cell
  uint8_t capHeight;         // height of a capital letter, for centring text
};

constexpr uint8_t UI_FIRST_CHAR = 32;
constexpr uint8_t UI_LAST_CHAR  = 126;
""")
    total = 0
    for name, file, size, chars in FACES:
        ascent, descent, cap_h, glyphs = render_face(file, size, chars)
        bitmap = bytearray()
        rows = []
        for ch in ALL:
            g = glyphs[ch]
            if g is None:
                rows.append((0, 0, 0, 0, round(size * 0.3), 0))
                continue
            w, h, xoff, yoff, adv, data = g
            rows.append((w, h, xoff, yoff, adv, len(bitmap)))
            bitmap += data
        assert len(bitmap) < 65536
        total += len(bitmap) + 7 * len(rows)
        out.append("// %s: %s %d px, %d bytes of bitmap" % (name, file.replace(".otf", ""), size, len(bitmap)))
        out.append("const UiGlyph UI_%s_GLYPHS[] PROGMEM = {" % name)
        for ch, r in zip(ALL, rows):
            out.append("  { %d, %d, %d, %d, %d, %d }," % r)
        out.append("};")
        out.append("const uint8_t UI_%s_BITMAPS[] PROGMEM = {" % name)
        for i in range(0, len(bitmap), 24):
            out.append("  " + ", ".join("0x%02X" % b for b in bitmap[i:i + 24]) + ",")
        out.append("};")
        out.append("const UiFont UI_FONT_%s = { UI_%s_GLYPHS, UI_%s_BITMAPS, %d, %d, %d };" % (name, name, name, ascent, ascent + descent, cap_h))
        out.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print("wrote %s (%d bytes of font data)" % (os.path.normpath(OUT), total))


main()
